#!/bin/bash
# mikrotik-inventory.sh - Pull config/inventory from a MikroTik router
# Pattern: https://netstack.org/docs/ops/storage-index/
# Run by: administrator (needs router credentials)
# Usage: bash mikrotik-inventory.sh <router-ip> <username> > output.md
#
# This script SSHs into a MikroTik and pulls identity, hardware, interfaces,
# IPs, routes, DHCP leases, and firewall summary. Output is markdown.

set -uo pipefail

ROUTER_IP="${1:-192.168.9.1}"
USER="${2:-admin}"
DATE=$(date +%Y-%m-%d)

SSH="ssh -o StrictHostKeyChecking=accept-new ${USER}@${ROUTER_IP}"

echo "# MikroTik Inventory: ${ROUTER_IP}"
echo ""
echo "**Scanned:** ${DATE}"
echo "**By:** $(whoami)@$(hostname)"
echo ""

echo "## Identity"
$SSH "/system identity print" 2>/dev/null
echo ""

echo "## Hardware"
$SSH "/system resource print" 2>/dev/null
echo ""

echo "## RouterOS Version"
$SSH "/system package print" 2>/dev/null
echo ""

echo "## Interfaces"
$SSH "/interface print" 2>/dev/null
echo ""

echo "## IP Addresses"
$SSH "/ip address print" 2>/dev/null
echo ""

echo "## IP Routes"
$SSH "/ip route print" 2>/dev/null
echo ""

echo "## DHCP Leases"
$SSH "/ip dhcp-server lease print" 2>/dev/null
echo ""

echo "## Firewall Filter (summary)"
$SSH "/ip firewall filter print brief" 2>/dev/null
echo ""

echo "## Firewall NAT"
$SSH "/ip firewall nat print brief" 2>/dev/null
echo ""

echo "---"
echo "*Generated by mikrotik-inventory.sh on ${DATE}*"
echo "*Pattern: https://netstack.org/docs/lan/network/*"
